<?php
/**
 * Created by PhpStorm.
 * User: james
 * Date: 2018/12/3
 * Time: 2:37 PM
 */

namespace data;


class business_statistics_view extends view
{
    public function printBussinessDetails($data)
    {
        $this->_file = fopen($this->file_name, "w");
        $re = $this->get_text($data);
        fwrite($this->_file, $re);
    }

    /**
     * @param $data
     */
    public function get_text($data)
    {
        $re = "\n";
        $keys=["id10",
"id20",
"id21",
"id22",
"id23",
"id24",
"id25",
"id27",
"id28",
"id29",
"id311",
"id351",
"id371",
"id431",
"id451",
"id471",
"id531",
"id551",
"id571",
"id591",
"id731",
"id771",
"id791",
"id851",
"id871",
"id891",
"id898",
"id931",
"id951",
"id971",
"id991"];

        foreach ($keys as $key ) {
            $re .= $key."\t";
            $pro_data=$data[$key];
            $re .= $pro_data['uploadfile'] . "\t";
            $re .= $pro_data['all_bill'] . "\t";
            $re .= $pro_data['wrong_bill'] . "\t";
            $re .= $pro_data['reject_num'] . "\t";
            $re .= $pro_data['rightbill'] . "\t";
            $re .= $pro_data['dispatchfile'] . "\t";
            $re .= $pro_data['dispatchbill'] . "\t";
            $re .= $pro_data['own_wrong_bill'] . "\t";
            $re .= "\n";
        }

        echo $re;
        return $re;
    }

    public function print_data($data)
    {
        $this->printBussinessDetails($data); // TODO: Change the autogenerated stub
    }

}

