<?php
/**
 * Created by PhpStorm.
 * User: james
 * Date: 2019-01-14
 * Time: 15:20
 */

namespace data;


class top_three_view extends view
{
    public function printTopThree($data)
    {

        $this->_file = fopen($this->file_name, "w");
        $re = $this->get_text($data);
        fwrite($this->_file, $re);
    }

    /**
     * @param $data
     */
    public function get_text($data)
    {
        $re = "\n";
        $down = $data[0];
        $up = $data[1];
        foreach ($down as $pro_data) {
            $re .= $pro_data['err_code'] . "\t";
            $re .= $pro_data['cnt'] . "\t";
            $re .= $pro_data['pro'] . "\t";

            $re .= "\n";
        }
        foreach ($up as $pro_data) {
            $re .= $pro_data['err_code'] . "\t";
            $re .= $pro_data['cnt'] . "\t";
            $re .= $pro_data['pro'] . "\t";

            $re .= "\n";
        }

        return $re;
    }

    public function print_data($data)
    {
        $this->printTopThree($data); // TODO: Change the autogenerated stub
    }
}